// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/communitybridge/easycla/cla-backend-go/v2/acs-service/models"
)

// NewCreateRolePolicyParams creates a new CreateRolePolicyParams object
// with the default values initialized.
func NewCreateRolePolicyParams() *CreateRolePolicyParams {
	var ()
	return &CreateRolePolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRolePolicyParamsWithTimeout creates a new CreateRolePolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRolePolicyParamsWithTimeout(timeout time.Duration) *CreateRolePolicyParams {
	var ()
	return &CreateRolePolicyParams{

		timeout: timeout,
	}
}

// NewCreateRolePolicyParamsWithContext creates a new CreateRolePolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRolePolicyParamsWithContext(ctx context.Context) *CreateRolePolicyParams {
	var ()
	return &CreateRolePolicyParams{

		Context: ctx,
	}
}

// NewCreateRolePolicyParamsWithHTTPClient creates a new CreateRolePolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRolePolicyParamsWithHTTPClient(client *http.Client) *CreateRolePolicyParams {
	var ()
	return &CreateRolePolicyParams{
		HTTPClient: client,
	}
}

/*CreateRolePolicyParams contains all the parameters to send to the API endpoint
for the create role policy operation typically these are written to a http.Request
*/
type CreateRolePolicyParams struct {

	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string
	/*ID
	  The role id.

	*/
	ID string
	/*PolicyIds
	  One or more policies

	*/
	PolicyIds []*models.CreateAttachPolicy

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create role policy params
func (o *CreateRolePolicyParams) WithTimeout(timeout time.Duration) *CreateRolePolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create role policy params
func (o *CreateRolePolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create role policy params
func (o *CreateRolePolicyParams) WithContext(ctx context.Context) *CreateRolePolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create role policy params
func (o *CreateRolePolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create role policy params
func (o *CreateRolePolicyParams) WithHTTPClient(client *http.Client) *CreateRolePolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create role policy params
func (o *CreateRolePolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmptyHeader adds the emptyHeader to the create role policy params
func (o *CreateRolePolicyParams) WithEmptyHeader(emptyHeader string) *CreateRolePolicyParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the create role policy params
func (o *CreateRolePolicyParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the create role policy params
func (o *CreateRolePolicyParams) WithXEMAIL(xEMAIL *string) *CreateRolePolicyParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the create role policy params
func (o *CreateRolePolicyParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the create role policy params
func (o *CreateRolePolicyParams) WithXREQUESTID(xREQUESTID *string) *CreateRolePolicyParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the create role policy params
func (o *CreateRolePolicyParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the create role policy params
func (o *CreateRolePolicyParams) WithXUSERNAME(xUSERNAME *string) *CreateRolePolicyParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the create role policy params
func (o *CreateRolePolicyParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WithID adds the id to the create role policy params
func (o *CreateRolePolicyParams) WithID(id string) *CreateRolePolicyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create role policy params
func (o *CreateRolePolicyParams) SetID(id string) {
	o.ID = id
}

// WithPolicyIds adds the policyIds to the create role policy params
func (o *CreateRolePolicyParams) WithPolicyIds(policyIds []*models.CreateAttachPolicy) *CreateRolePolicyParams {
	o.SetPolicyIds(policyIds)
	return o
}

// SetPolicyIds adds the policyIds to the create role policy params
func (o *CreateRolePolicyParams) SetPolicyIds(policyIds []*models.CreateAttachPolicy) {
	o.PolicyIds = policyIds
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRolePolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.PolicyIds != nil {
		if err := r.SetBodyParam(o.PolicyIds); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
