// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteRolePoliciesParams creates a new DeleteRolePoliciesParams object
// with the default values initialized.
func NewDeleteRolePoliciesParams() *DeleteRolePoliciesParams {
	var ()
	return &DeleteRolePoliciesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRolePoliciesParamsWithTimeout creates a new DeleteRolePoliciesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRolePoliciesParamsWithTimeout(timeout time.Duration) *DeleteRolePoliciesParams {
	var ()
	return &DeleteRolePoliciesParams{

		timeout: timeout,
	}
}

// NewDeleteRolePoliciesParamsWithContext creates a new DeleteRolePoliciesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRolePoliciesParamsWithContext(ctx context.Context) *DeleteRolePoliciesParams {
	var ()
	return &DeleteRolePoliciesParams{

		Context: ctx,
	}
}

// NewDeleteRolePoliciesParamsWithHTTPClient creates a new DeleteRolePoliciesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRolePoliciesParamsWithHTTPClient(client *http.Client) *DeleteRolePoliciesParams {
	var ()
	return &DeleteRolePoliciesParams{
		HTTPClient: client,
	}
}

/*DeleteRolePoliciesParams contains all the parameters to send to the API endpoint
for the delete role policies operation typically these are written to a http.Request
*/
type DeleteRolePoliciesParams struct {

	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string
	/*ID
	  The role id.

	*/
	ID string
	/*PolicyID
	  The policy id.

	*/
	PolicyID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete role policies params
func (o *DeleteRolePoliciesParams) WithTimeout(timeout time.Duration) *DeleteRolePoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete role policies params
func (o *DeleteRolePoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete role policies params
func (o *DeleteRolePoliciesParams) WithContext(ctx context.Context) *DeleteRolePoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete role policies params
func (o *DeleteRolePoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete role policies params
func (o *DeleteRolePoliciesParams) WithHTTPClient(client *http.Client) *DeleteRolePoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete role policies params
func (o *DeleteRolePoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmptyHeader adds the emptyHeader to the delete role policies params
func (o *DeleteRolePoliciesParams) WithEmptyHeader(emptyHeader string) *DeleteRolePoliciesParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the delete role policies params
func (o *DeleteRolePoliciesParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the delete role policies params
func (o *DeleteRolePoliciesParams) WithXEMAIL(xEMAIL *string) *DeleteRolePoliciesParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the delete role policies params
func (o *DeleteRolePoliciesParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the delete role policies params
func (o *DeleteRolePoliciesParams) WithXREQUESTID(xREQUESTID *string) *DeleteRolePoliciesParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the delete role policies params
func (o *DeleteRolePoliciesParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the delete role policies params
func (o *DeleteRolePoliciesParams) WithXUSERNAME(xUSERNAME *string) *DeleteRolePoliciesParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the delete role policies params
func (o *DeleteRolePoliciesParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WithID adds the id to the delete role policies params
func (o *DeleteRolePoliciesParams) WithID(id string) *DeleteRolePoliciesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete role policies params
func (o *DeleteRolePoliciesParams) SetID(id string) {
	o.ID = id
}

// WithPolicyID adds the policyID to the delete role policies params
func (o *DeleteRolePoliciesParams) WithPolicyID(policyID string) *DeleteRolePoliciesParams {
	o.SetPolicyID(policyID)
	return o
}

// SetPolicyID adds the policyId to the delete role policies params
func (o *DeleteRolePoliciesParams) SetPolicyID(policyID string) {
	o.PolicyID = policyID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRolePoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param policyId
	if err := r.SetPathParam("policyId", o.PolicyID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
