// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/communitybridge/easycla/cla-backend-go/v2/acs-service/models"
)

// NewUpdatePolicyStatementParams creates a new UpdatePolicyStatementParams object
// with the default values initialized.
func NewUpdatePolicyStatementParams() *UpdatePolicyStatementParams {
	var ()
	return &UpdatePolicyStatementParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePolicyStatementParamsWithTimeout creates a new UpdatePolicyStatementParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePolicyStatementParamsWithTimeout(timeout time.Duration) *UpdatePolicyStatementParams {
	var ()
	return &UpdatePolicyStatementParams{

		timeout: timeout,
	}
}

// NewUpdatePolicyStatementParamsWithContext creates a new UpdatePolicyStatementParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdatePolicyStatementParamsWithContext(ctx context.Context) *UpdatePolicyStatementParams {
	var ()
	return &UpdatePolicyStatementParams{

		Context: ctx,
	}
}

// NewUpdatePolicyStatementParamsWithHTTPClient creates a new UpdatePolicyStatementParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdatePolicyStatementParamsWithHTTPClient(client *http.Client) *UpdatePolicyStatementParams {
	var ()
	return &UpdatePolicyStatementParams{
		HTTPClient: client,
	}
}

/*UpdatePolicyStatementParams contains all the parameters to send to the API endpoint
for the update policy statement operation typically these are written to a http.Request
*/
type UpdatePolicyStatementParams struct {

	/*Body*/
	Body *models.CreateUpdateStatement
	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string
	/*PolicyID
	  The policy id.

	*/
	PolicyID string
	/*StatementID
	  The statement id.

	*/
	StatementID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update policy statement params
func (o *UpdatePolicyStatementParams) WithTimeout(timeout time.Duration) *UpdatePolicyStatementParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update policy statement params
func (o *UpdatePolicyStatementParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update policy statement params
func (o *UpdatePolicyStatementParams) WithContext(ctx context.Context) *UpdatePolicyStatementParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update policy statement params
func (o *UpdatePolicyStatementParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update policy statement params
func (o *UpdatePolicyStatementParams) WithHTTPClient(client *http.Client) *UpdatePolicyStatementParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update policy statement params
func (o *UpdatePolicyStatementParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update policy statement params
func (o *UpdatePolicyStatementParams) WithBody(body *models.CreateUpdateStatement) *UpdatePolicyStatementParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update policy statement params
func (o *UpdatePolicyStatementParams) SetBody(body *models.CreateUpdateStatement) {
	o.Body = body
}

// WithEmptyHeader adds the emptyHeader to the update policy statement params
func (o *UpdatePolicyStatementParams) WithEmptyHeader(emptyHeader string) *UpdatePolicyStatementParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the update policy statement params
func (o *UpdatePolicyStatementParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the update policy statement params
func (o *UpdatePolicyStatementParams) WithXEMAIL(xEMAIL *string) *UpdatePolicyStatementParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the update policy statement params
func (o *UpdatePolicyStatementParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the update policy statement params
func (o *UpdatePolicyStatementParams) WithXREQUESTID(xREQUESTID *string) *UpdatePolicyStatementParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the update policy statement params
func (o *UpdatePolicyStatementParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the update policy statement params
func (o *UpdatePolicyStatementParams) WithXUSERNAME(xUSERNAME *string) *UpdatePolicyStatementParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the update policy statement params
func (o *UpdatePolicyStatementParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WithPolicyID adds the policyID to the update policy statement params
func (o *UpdatePolicyStatementParams) WithPolicyID(policyID string) *UpdatePolicyStatementParams {
	o.SetPolicyID(policyID)
	return o
}

// SetPolicyID adds the policyId to the update policy statement params
func (o *UpdatePolicyStatementParams) SetPolicyID(policyID string) {
	o.PolicyID = policyID
}

// WithStatementID adds the statementID to the update policy statement params
func (o *UpdatePolicyStatementParams) WithStatementID(statementID string) *UpdatePolicyStatementParams {
	o.SetStatementID(statementID)
	return o
}

// SetStatementID adds the statementId to the update policy statement params
func (o *UpdatePolicyStatementParams) SetStatementID(statementID string) {
	o.StatementID = statementID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePolicyStatementParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	// path param policyId
	if err := r.SetPathParam("policyId", o.PolicyID); err != nil {
		return err
	}

	// path param statementId
	if err := r.SetPathParam("statementId", o.StatementID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
