// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContextRoles ContextRoles is entity to represent role that belongs to Role
//
// swagger:model ContextRoles
type ContextRoles struct {

	// Context name
	Context string `json:"context,omitempty"`

	// ID reference to role
	RoleID string `json:"role_id,omitempty"`

	// Role name
	RoleName string `json:"role_name,omitempty"`
}

// Validate validates this context roles
func (m *ContextRoles) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContextRoles) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContextRoles) UnmarshalBinary(b []byte) error {
	var res ContextRoles
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
