// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateUpdateResourceAction CreateUpdateResourceAction is entity to represent data that is required to create or update resource action
//
// swagger:model CreateUpdateResourceAction
type CreateUpdateResourceAction struct {

	// action ids
	ActionIds []string `json:"action_ids"`

	// Resource Action name, restricted to alphanum and these special characters: +=,.@-_. Max Length: 128.
	// Pattern: ^[\w+\+=,\.@\-_]{0,128}$
	Name string `json:"name,omitempty"`

	// Unique ID reference of the resource action
	// Read Only: true
	ResourceActionID string `json:"resource_action_id,omitempty"`

	// Unique ID reference of the service
	ServiceID string `json:"service_id,omitempty"`
}

// Validate validates this create update resource action
func (m *CreateUpdateResourceAction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateUpdateResourceAction) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", string(m.Name), `^[\w+\+=,\.@\-_]{0,128}$`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateUpdateResourceAction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateUpdateResourceAction) UnmarshalBinary(b []byte) error {
	var res CreateUpdateResourceAction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
