// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListMetadata List Metadata
//
// swagger:model List-Metadata
type ListMetadata struct {

	// The page offset for fetching subsequent pages of results, value must be a non-negative integer value
	Offset int64 `json:"Offset"`

	// The number of results per page, value must be a positive integer value
	PageSize int64 `json:"PageSize"`

	// The total number results available
	TotalSize int64 `json:"TotalSize"`
}

// Validate validates this list metadata
func (m *ListMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListMetadata) UnmarshalBinary(b []byte) error {
	var res ListMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
