// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Roles Roles is entity to represent array of data consist of role, object_ids and object_type
//
// swagger:model Roles
type Roles struct {

	// Array of id reference to object
	ObjectIds []string `json:"object_ids"`

	// ID reference to object type
	ObjectTypeID int64 `json:"object_type_id,omitempty"`

	// ID reference to role
	// Read Only: true
	RoleID int64 `json:"role_id,omitempty"`
}

// Validate validates this roles
func (m *Roles) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Roles) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Roles) UnmarshalBinary(b []byte) error {
	var res Roles
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
