// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceObj ServiceObj is entity to represent object as part of ServiceResourceAction
//
// swagger:model ServiceObj
type ServiceObj struct {

	// Unique ID of Service Object
	// Read Only: true
	ID string `json:"id,omitempty"`

	// Service Object name
	Name string `json:"name,omitempty"`
}

// Validate validates this service obj
func (m *ServiceObj) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceObj) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceObj) UnmarshalBinary(b []byte) error {
	var res ServiceObj
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
