// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StatementAction StatementAction is entity to represent set of action_id and action name that belongs to Statement
//
// swagger:model StatementAction
type StatementAction struct {

	// ID reference to action
	// Read Only: true
	ActionID string `json:"action_id,omitempty"`

	// Action name
	Name string `json:"name,omitempty"`
}

// Validate validates this statement action
func (m *StatementAction) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StatementAction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StatementAction) UnmarshalBinary(b []byte) error {
	var res StatementAction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
