// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectListParams creates a new GetProjectListParams object
// with the default values initialized.
func NewGetProjectListParams() *GetProjectListParams {
	var ()
	return &GetProjectListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectListParamsWithTimeout creates a new GetProjectListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProjectListParamsWithTimeout(timeout time.Duration) *GetProjectListParams {
	var ()
	return &GetProjectListParams{

		timeout: timeout,
	}
}

// NewGetProjectListParamsWithContext creates a new GetProjectListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProjectListParamsWithContext(ctx context.Context) *GetProjectListParams {
	var ()
	return &GetProjectListParams{

		Context: ctx,
	}
}

// NewGetProjectListParamsWithHTTPClient creates a new GetProjectListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProjectListParamsWithHTTPClient(client *http.Client) *GetProjectListParams {
	var ()
	return &GetProjectListParams{
		HTTPClient: client,
	}
}

/*GetProjectListParams contains all the parameters to send to the API endpoint
for the get project list operation typically these are written to a http.Request
*/
type GetProjectListParams struct {

	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string
	/*Limit
	  The maximum amount of projects returned.

	*/
	Limit *int64
	/*Offset
	  The offset from where to start looking.

	*/
	Offset *int64
	/*Search
	  The search term to match with from the beginning

	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get project list params
func (o *GetProjectListParams) WithTimeout(timeout time.Duration) *GetProjectListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project list params
func (o *GetProjectListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project list params
func (o *GetProjectListParams) WithContext(ctx context.Context) *GetProjectListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project list params
func (o *GetProjectListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project list params
func (o *GetProjectListParams) WithHTTPClient(client *http.Client) *GetProjectListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project list params
func (o *GetProjectListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmptyHeader adds the emptyHeader to the get project list params
func (o *GetProjectListParams) WithEmptyHeader(emptyHeader string) *GetProjectListParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the get project list params
func (o *GetProjectListParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the get project list params
func (o *GetProjectListParams) WithXEMAIL(xEMAIL *string) *GetProjectListParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the get project list params
func (o *GetProjectListParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the get project list params
func (o *GetProjectListParams) WithXREQUESTID(xREQUESTID *string) *GetProjectListParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the get project list params
func (o *GetProjectListParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the get project list params
func (o *GetProjectListParams) WithXUSERNAME(xUSERNAME *string) *GetProjectListParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the get project list params
func (o *GetProjectListParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WithLimit adds the limit to the get project list params
func (o *GetProjectListParams) WithLimit(limit *int64) *GetProjectListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get project list params
func (o *GetProjectListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get project list params
func (o *GetProjectListParams) WithOffset(offset *int64) *GetProjectListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get project list params
func (o *GetProjectListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSearch adds the search to the get project list params
func (o *GetProjectListParams) WithSearch(search *string) *GetProjectListParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get project list params
func (o *GetProjectListParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
