// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package warden

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/communitybridge/easycla/cla-backend-go/v2/acs-service/models"
)

// NewPostWardenParams creates a new PostWardenParams object
// with the default values initialized.
func NewPostWardenParams() *PostWardenParams {
	var ()
	return &PostWardenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostWardenParamsWithTimeout creates a new PostWardenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostWardenParamsWithTimeout(timeout time.Duration) *PostWardenParams {
	var ()
	return &PostWardenParams{

		timeout: timeout,
	}
}

// NewPostWardenParamsWithContext creates a new PostWardenParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostWardenParamsWithContext(ctx context.Context) *PostWardenParams {
	var ()
	return &PostWardenParams{

		Context: ctx,
	}
}

// NewPostWardenParamsWithHTTPClient creates a new PostWardenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostWardenParamsWithHTTPClient(client *http.Client) *PostWardenParams {
	var ()
	return &PostWardenParams{
		HTTPClient: client,
	}
}

/*PostWardenParams contains all the parameters to send to the API endpoint
for the post warden operation typically these are written to a http.Request
*/
type PostWardenParams struct {

	/*AccessRequest
	  The AccessRequest is the warden's request object.

	*/
	AccessRequest *models.AccessRequest
	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post warden params
func (o *PostWardenParams) WithTimeout(timeout time.Duration) *PostWardenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post warden params
func (o *PostWardenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post warden params
func (o *PostWardenParams) WithContext(ctx context.Context) *PostWardenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post warden params
func (o *PostWardenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post warden params
func (o *PostWardenParams) WithHTTPClient(client *http.Client) *PostWardenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post warden params
func (o *PostWardenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessRequest adds the accessRequest to the post warden params
func (o *PostWardenParams) WithAccessRequest(accessRequest *models.AccessRequest) *PostWardenParams {
	o.SetAccessRequest(accessRequest)
	return o
}

// SetAccessRequest adds the accessRequest to the post warden params
func (o *PostWardenParams) SetAccessRequest(accessRequest *models.AccessRequest) {
	o.AccessRequest = accessRequest
}

// WithEmptyHeader adds the emptyHeader to the post warden params
func (o *PostWardenParams) WithEmptyHeader(emptyHeader string) *PostWardenParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the post warden params
func (o *PostWardenParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the post warden params
func (o *PostWardenParams) WithXEMAIL(xEMAIL *string) *PostWardenParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the post warden params
func (o *PostWardenParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the post warden params
func (o *PostWardenParams) WithXREQUESTID(xREQUESTID *string) *PostWardenParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the post warden params
func (o *PostWardenParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the post warden params
func (o *PostWardenParams) WithXUSERNAME(xUSERNAME *string) *PostWardenParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the post warden params
func (o *PostWardenParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WriteToRequest writes these params to a swagger request
func (o *PostWardenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccessRequest != nil {
		if err := r.SetBodyParam(o.AccessRequest); err != nil {
			return err
		}
	}

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
