package template

import (
	"context"

	"github.com/LF-Engineering/cla-monorepo/cla-backend-go/gen/models"
)

type Repository interface {
	GetTemplates(ctx context.Context) ([]models.Template, error)
}

type repository struct {
}

func NewRepository() repository {
	return repository{}
}

func (repo repository) GetTemplates(ctx context.Context) ([]models.Template, error) {
	apacheTemplate := models.Template{
		Name:        "Apache Style",
		Description: "For use of projects under the Apache style of CLA. ",
		MetaFields: []*models.MetaField{
			&models.MetaField{
				Name:             "Project Name",
				Description:      "Project's Full Name.",
				TemplateVariable: "PROJECT_NAME",
			},
			&models.MetaField{
				Name:             "Short Project Name",
				Description:      "The short version of the project’s name, used as a reference in the CLA.",
				TemplateVariable: "SHORT_PROJECT_NAME",
			},
			&models.MetaField{
				Name:             "Contact Email Address",
				Description:      "The E-Mail Address of the Person managing the CLA. ",
				TemplateVariable: "CONTACT_EMAIL",
			},
		},
		IclaFields: []*models.Field{
			&models.Field{
				Name:         "Full Name",
				AnchorString: "Full name:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        360,
				Height:       20,
				OffsetX:      72,
				OffsetY:      -8,
			},
			&models.Field{
				Name:         "Public Name",
				AnchorString: "Public name:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        345,
				Height:       20,
				OffsetX:      84,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Mailing Address1",
				AnchorString: "Mailing Address:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        325,
				Height:       20,
				OffsetX:      117,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Mailing Address2",
				AnchorString: "Mailing Address:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        420,
				Height:       20,
				OffsetX:      0,
				OffsetY:      29,
			},
			&models.Field{
				Name:         "Country",
				AnchorString: "Country:",
				FieldType:    "text_unlocked",
				IsOptional:   true,
				IsEditable:   false,
				Width:        350,
				Height:       20,
				OffsetX:      60,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Telephone",
				AnchorString: "Telephone:",
				FieldType:    "text_unlocked",
				IsOptional:   true,
				IsEditable:   false,
				Width:        350,
				Height:       20,
				OffsetX:      70,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Email",
				AnchorString: "E-Mail:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        380,
				Height:       20,
				OffsetX:      50,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Please Sign",
				AnchorString: "Please Sign:",
				FieldType:    "sign",
				IsOptional:   false,
				IsEditable:   false,
				Width:        0,
				Height:       0,
				OffsetX:      140,
				OffsetY:      -5,
			},
			&models.Field{
				Name:         "Date",
				AnchorString: "Date:",
				FieldType:    "date",
				IsOptional:   false,
				IsEditable:   false,
				Width:        0,
				Height:       0,
				OffsetX:      60,
				OffsetY:      -7,
			},
		},
		CclaFields: []*models.Field{
			&models.Field{
				Name:         "Corporation Name",
				AnchorString: "Corporation Name:",
				FieldType:    "text",
				IsOptional:   false,
				IsEditable:   false,
				Width:        355,
				Height:       20,
				OffsetX:      140,
				OffsetY:      -5,
			},
			&models.Field{
				Name:         "Corporation Address1",
				AnchorString: "Corporation Address:",
				FieldType:    "text",
				IsOptional:   false,
				IsEditable:   false,
				Width:        340,
				Height:       20,
				OffsetX:      140,
				OffsetY:      -8,
			},
			&models.Field{
				Name:         "Corporation Address2",
				AnchorString: "Corporation Address:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        400,
				Height:       20,
				OffsetX:      0,
				OffsetY:      29,
			},
			&models.Field{
				Name:         "Corporation Address3",
				AnchorString: "Corporation Address:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        400,
				Height:       20,
				OffsetX:      0,
				OffsetY:      64,
			},
			&models.Field{
				Name:         "Point of Contact",
				AnchorString: "Point of Contact:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        340,
				Height:       20,
				OffsetX:      120,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Email",
				AnchorString: "E-Mail:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        340,
				Height:       20,
				OffsetX:      50,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Telephone",
				AnchorString: "Telephone:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        405,
				Height:       20,
				OffsetX:      70,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Please Sign",
				AnchorString: "Please sign:",
				FieldType:    "sign",
				IsOptional:   false,
				IsEditable:   false,
				Width:        0,
				Height:       0,
				OffsetX:      140,
				OffsetY:      -6,
			},
			&models.Field{
				Name:         "Date",
				AnchorString: "Date:",
				FieldType:    "date",
				IsOptional:   false,
				IsEditable:   false,
				Width:        0,
				Height:       0,
				OffsetX:      80,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Title",
				AnchorString: "Title:",
				FieldType:    "text_unlocked",
				IsOptional:   false,
				IsEditable:   false,
				Width:        430,
				Height:       20,
				OffsetX:      40,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Corporation",
				AnchorString: "Corporation:",
				FieldType:    "text",
				IsOptional:   false,
				IsEditable:   false,
				Width:        385,
				Height:       20,
				OffsetX:      100,
				OffsetY:      -7,
			},
			&models.Field{
				Name:         "Schedule A",
				AnchorString: "Schedule A:",
				FieldType:    "text",
				IsOptional:   false,
				IsEditable:   false,
				Width:        550,
				Height:       600,
				OffsetX:      0,
				OffsetY:      150,
			},
		},
		HTMLBody: "<html> </html>",
	}
	templates := []models.Template{}

	templates = append(templates, apacheTemplate)
	return templates, nil
}
