// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package group_role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteGroupGrantParams creates a new DeleteGroupGrantParams object
// with the default values initialized.
func NewDeleteGroupGrantParams() *DeleteGroupGrantParams {
	var ()
	return &DeleteGroupGrantParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteGroupGrantParamsWithTimeout creates a new DeleteGroupGrantParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteGroupGrantParamsWithTimeout(timeout time.Duration) *DeleteGroupGrantParams {
	var ()
	return &DeleteGroupGrantParams{

		timeout: timeout,
	}
}

// NewDeleteGroupGrantParamsWithContext creates a new DeleteGroupGrantParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteGroupGrantParamsWithContext(ctx context.Context) *DeleteGroupGrantParams {
	var ()
	return &DeleteGroupGrantParams{

		Context: ctx,
	}
}

// NewDeleteGroupGrantParamsWithHTTPClient creates a new DeleteGroupGrantParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteGroupGrantParamsWithHTTPClient(client *http.Client) *DeleteGroupGrantParams {
	var ()
	return &DeleteGroupGrantParams{
		HTTPClient: client,
	}
}

/*DeleteGroupGrantParams contains all the parameters to send to the API endpoint
for the delete group grant operation typically these are written to a http.Request
*/
type DeleteGroupGrantParams struct {

	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string
	/*ID
	  The group id.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete group grant params
func (o *DeleteGroupGrantParams) WithTimeout(timeout time.Duration) *DeleteGroupGrantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete group grant params
func (o *DeleteGroupGrantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete group grant params
func (o *DeleteGroupGrantParams) WithContext(ctx context.Context) *DeleteGroupGrantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete group grant params
func (o *DeleteGroupGrantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete group grant params
func (o *DeleteGroupGrantParams) WithHTTPClient(client *http.Client) *DeleteGroupGrantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete group grant params
func (o *DeleteGroupGrantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmptyHeader adds the emptyHeader to the delete group grant params
func (o *DeleteGroupGrantParams) WithEmptyHeader(emptyHeader string) *DeleteGroupGrantParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the delete group grant params
func (o *DeleteGroupGrantParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the delete group grant params
func (o *DeleteGroupGrantParams) WithXEMAIL(xEMAIL *string) *DeleteGroupGrantParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the delete group grant params
func (o *DeleteGroupGrantParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the delete group grant params
func (o *DeleteGroupGrantParams) WithXREQUESTID(xREQUESTID *string) *DeleteGroupGrantParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the delete group grant params
func (o *DeleteGroupGrantParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the delete group grant params
func (o *DeleteGroupGrantParams) WithXUSERNAME(xUSERNAME *string) *DeleteGroupGrantParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the delete group grant params
func (o *DeleteGroupGrantParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WithID adds the id to the delete group grant params
func (o *DeleteGroupGrantParams) WithID(id string) *DeleteGroupGrantParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete group grant params
func (o *DeleteGroupGrantParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteGroupGrantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
