// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/communitybridge/easycla/cla-backend-go/v2/acs-service/models"
)

// NewCreateServiceParams creates a new CreateServiceParams object
// with the default values initialized.
func NewCreateServiceParams() *CreateServiceParams {
	var ()
	return &CreateServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateServiceParamsWithTimeout creates a new CreateServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateServiceParamsWithTimeout(timeout time.Duration) *CreateServiceParams {
	var ()
	return &CreateServiceParams{

		timeout: timeout,
	}
}

// NewCreateServiceParamsWithContext creates a new CreateServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateServiceParamsWithContext(ctx context.Context) *CreateServiceParams {
	var ()
	return &CreateServiceParams{

		Context: ctx,
	}
}

// NewCreateServiceParamsWithHTTPClient creates a new CreateServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateServiceParamsWithHTTPClient(client *http.Client) *CreateServiceParams {
	var ()
	return &CreateServiceParams{
		HTTPClient: client,
	}
}

/*CreateServiceParams contains all the parameters to send to the API endpoint
for the create service operation typically these are written to a http.Request
*/
type CreateServiceParams struct {

	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string
	/*Objecttype
	  The type object to create

	*/
	Objecttype *models.CreateService

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create service params
func (o *CreateServiceParams) WithTimeout(timeout time.Duration) *CreateServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create service params
func (o *CreateServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create service params
func (o *CreateServiceParams) WithContext(ctx context.Context) *CreateServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create service params
func (o *CreateServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create service params
func (o *CreateServiceParams) WithHTTPClient(client *http.Client) *CreateServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create service params
func (o *CreateServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmptyHeader adds the emptyHeader to the create service params
func (o *CreateServiceParams) WithEmptyHeader(emptyHeader string) *CreateServiceParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the create service params
func (o *CreateServiceParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the create service params
func (o *CreateServiceParams) WithXEMAIL(xEMAIL *string) *CreateServiceParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the create service params
func (o *CreateServiceParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the create service params
func (o *CreateServiceParams) WithXREQUESTID(xREQUESTID *string) *CreateServiceParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the create service params
func (o *CreateServiceParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the create service params
func (o *CreateServiceParams) WithXUSERNAME(xUSERNAME *string) *CreateServiceParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the create service params
func (o *CreateServiceParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WithObjecttype adds the objecttype to the create service params
func (o *CreateServiceParams) WithObjecttype(objecttype *models.CreateService) *CreateServiceParams {
	o.SetObjecttype(objecttype)
	return o
}

// SetObjecttype adds the objecttype to the create service params
func (o *CreateServiceParams) SetObjecttype(objecttype *models.CreateService) {
	o.Objecttype = objecttype
}

// WriteToRequest writes these params to a swagger request
func (o *CreateServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	if o.Objecttype != nil {
		if err := r.SetBodyParam(o.Objecttype); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
