// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/communitybridge/easycla/cla-backend-go/v2/acs-service/models"
)

// DeleteResourceReader is a Reader for the DeleteResource structure.
type DeleteResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteResourceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteResourceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteResourceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteResourceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteResourceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteResourceNoContent creates a DeleteResourceNoContent with default headers values
func NewDeleteResourceNoContent() *DeleteResourceNoContent {
	return &DeleteResourceNoContent{}
}

/*DeleteResourceNoContent handles this case with default header values.

An empty response
*/
type DeleteResourceNoContent struct {
}

func (o *DeleteResourceNoContent) Error() string {
	return fmt.Sprintf("[DELETE /resources/{id}][%d] deleteResourceNoContent ", 204)
}

func (o *DeleteResourceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteResourceBadRequest creates a DeleteResourceBadRequest with default headers values
func NewDeleteResourceBadRequest() *DeleteResourceBadRequest {
	return &DeleteResourceBadRequest{}
}

/*DeleteResourceBadRequest handles this case with default header values.

Invalid request
*/
type DeleteResourceBadRequest struct {
	/*Unique request ID to help in tracing and debugging
	 */
	XREQUESTID string

	Payload *models.ErrorResponse
}

func (o *DeleteResourceBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /resources/{id}][%d] deleteResourceBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteResourceBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteResourceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-REQUEST-ID
	o.XREQUESTID = response.GetHeader("X-REQUEST-ID")

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteResourceUnauthorized creates a DeleteResourceUnauthorized with default headers values
func NewDeleteResourceUnauthorized() *DeleteResourceUnauthorized {
	return &DeleteResourceUnauthorized{}
}

/*DeleteResourceUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteResourceUnauthorized struct {
	/*Unique request ID to help in tracing and debugging
	 */
	XREQUESTID string

	Payload *models.ErrorResponse
}

func (o *DeleteResourceUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /resources/{id}][%d] deleteResourceUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteResourceUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteResourceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-REQUEST-ID
	o.XREQUESTID = response.GetHeader("X-REQUEST-ID")

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteResourceForbidden creates a DeleteResourceForbidden with default headers values
func NewDeleteResourceForbidden() *DeleteResourceForbidden {
	return &DeleteResourceForbidden{}
}

/*DeleteResourceForbidden handles this case with default header values.

Insufficient privilege to execute action
*/
type DeleteResourceForbidden struct {
	/*Unique request ID to help in tracing and debugging
	 */
	XREQUESTID string

	Payload *models.ErrorResponse
}

func (o *DeleteResourceForbidden) Error() string {
	return fmt.Sprintf("[DELETE /resources/{id}][%d] deleteResourceForbidden  %+v", 403, o.Payload)
}

func (o *DeleteResourceForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteResourceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-REQUEST-ID
	o.XREQUESTID = response.GetHeader("X-REQUEST-ID")

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteResourceNotFound creates a DeleteResourceNotFound with default headers values
func NewDeleteResourceNotFound() *DeleteResourceNotFound {
	return &DeleteResourceNotFound{}
}

/*DeleteResourceNotFound handles this case with default header values.

Not found
*/
type DeleteResourceNotFound struct {
	/*Unique request ID to help in tracing and debugging
	 */
	XREQUESTID string

	Payload *models.ErrorResponse
}

func (o *DeleteResourceNotFound) Error() string {
	return fmt.Sprintf("[DELETE /resources/{id}][%d] deleteResourceNotFound  %+v", 404, o.Payload)
}

func (o *DeleteResourceNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteResourceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-REQUEST-ID
	o.XREQUESTID = response.GetHeader("X-REQUEST-ID")

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
