// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package action

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteActionParams creates a new DeleteActionParams object
// with the default values initialized.
func NewDeleteActionParams() *DeleteActionParams {
	var ()
	return &DeleteActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteActionParamsWithTimeout creates a new DeleteActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteActionParamsWithTimeout(timeout time.Duration) *DeleteActionParams {
	var ()
	return &DeleteActionParams{

		timeout: timeout,
	}
}

// NewDeleteActionParamsWithContext creates a new DeleteActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteActionParamsWithContext(ctx context.Context) *DeleteActionParams {
	var ()
	return &DeleteActionParams{

		Context: ctx,
	}
}

// NewDeleteActionParamsWithHTTPClient creates a new DeleteActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteActionParamsWithHTTPClient(client *http.Client) *DeleteActionParams {
	var ()
	return &DeleteActionParams{
		HTTPClient: client,
	}
}

/*DeleteActionParams contains all the parameters to send to the API endpoint
for the delete action operation typically these are written to a http.Request
*/
type DeleteActionParams struct {

	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string
	/*ID
	  The action id.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete action params
func (o *DeleteActionParams) WithTimeout(timeout time.Duration) *DeleteActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete action params
func (o *DeleteActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete action params
func (o *DeleteActionParams) WithContext(ctx context.Context) *DeleteActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete action params
func (o *DeleteActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete action params
func (o *DeleteActionParams) WithHTTPClient(client *http.Client) *DeleteActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete action params
func (o *DeleteActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmptyHeader adds the emptyHeader to the delete action params
func (o *DeleteActionParams) WithEmptyHeader(emptyHeader string) *DeleteActionParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the delete action params
func (o *DeleteActionParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the delete action params
func (o *DeleteActionParams) WithXEMAIL(xEMAIL *string) *DeleteActionParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the delete action params
func (o *DeleteActionParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the delete action params
func (o *DeleteActionParams) WithXREQUESTID(xREQUESTID *string) *DeleteActionParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the delete action params
func (o *DeleteActionParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the delete action params
func (o *DeleteActionParams) WithXUSERNAME(xUSERNAME *string) *DeleteActionParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the delete action params
func (o *DeleteActionParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WithID adds the id to the delete action params
func (o *DeleteActionParams) WithID(id string) *DeleteActionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete action params
func (o *DeleteActionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
