// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserDetailParams creates a new GetUserDetailParams object
// with the default values initialized.
func NewGetUserDetailParams() *GetUserDetailParams {
	var ()
	return &GetUserDetailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserDetailParamsWithTimeout creates a new GetUserDetailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserDetailParamsWithTimeout(timeout time.Duration) *GetUserDetailParams {
	var ()
	return &GetUserDetailParams{

		timeout: timeout,
	}
}

// NewGetUserDetailParamsWithContext creates a new GetUserDetailParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserDetailParamsWithContext(ctx context.Context) *GetUserDetailParams {
	var ()
	return &GetUserDetailParams{

		Context: ctx,
	}
}

// NewGetUserDetailParamsWithHTTPClient creates a new GetUserDetailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserDetailParamsWithHTTPClient(client *http.Client) *GetUserDetailParams {
	var ()
	return &GetUserDetailParams{
		HTTPClient: client,
	}
}

/*GetUserDetailParams contains all the parameters to send to the API endpoint
for the get user detail operation typically these are written to a http.Request
*/
type GetUserDetailParams struct {

	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string
	/*Username
	  The user name.

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user detail params
func (o *GetUserDetailParams) WithTimeout(timeout time.Duration) *GetUserDetailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user detail params
func (o *GetUserDetailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user detail params
func (o *GetUserDetailParams) WithContext(ctx context.Context) *GetUserDetailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user detail params
func (o *GetUserDetailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user detail params
func (o *GetUserDetailParams) WithHTTPClient(client *http.Client) *GetUserDetailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user detail params
func (o *GetUserDetailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmptyHeader adds the emptyHeader to the get user detail params
func (o *GetUserDetailParams) WithEmptyHeader(emptyHeader string) *GetUserDetailParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the get user detail params
func (o *GetUserDetailParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the get user detail params
func (o *GetUserDetailParams) WithXEMAIL(xEMAIL *string) *GetUserDetailParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the get user detail params
func (o *GetUserDetailParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the get user detail params
func (o *GetUserDetailParams) WithXREQUESTID(xREQUESTID *string) *GetUserDetailParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the get user detail params
func (o *GetUserDetailParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the get user detail params
func (o *GetUserDetailParams) WithXUSERNAME(xUSERNAME *string) *GetUserDetailParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the get user detail params
func (o *GetUserDetailParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WithUsername adds the username to the get user detail params
func (o *GetUserDetailParams) WithUsername(username string) *GetUserDetailParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get user detail params
func (o *GetUserDetailParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserDetailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
