// Code generated by go-swagger; DO NOT EDIT.

// Copyright The Linux Foundation and each contributor to CommunityBridge.
// SPDX-License-Identifier: MIT
//

package user_role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRoleUserScopesParams creates a new GetRoleUserScopesParams object
// with the default values initialized.
func NewGetRoleUserScopesParams() *GetRoleUserScopesParams {
	var ()
	return &GetRoleUserScopesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoleUserScopesParamsWithTimeout creates a new GetRoleUserScopesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRoleUserScopesParamsWithTimeout(timeout time.Duration) *GetRoleUserScopesParams {
	var ()
	return &GetRoleUserScopesParams{

		timeout: timeout,
	}
}

// NewGetRoleUserScopesParamsWithContext creates a new GetRoleUserScopesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRoleUserScopesParamsWithContext(ctx context.Context) *GetRoleUserScopesParams {
	var ()
	return &GetRoleUserScopesParams{

		Context: ctx,
	}
}

// NewGetRoleUserScopesParamsWithHTTPClient creates a new GetRoleUserScopesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRoleUserScopesParamsWithHTTPClient(client *http.Client) *GetRoleUserScopesParams {
	var ()
	return &GetRoleUserScopesParams{
		HTTPClient: client,
	}
}

/*GetRoleUserScopesParams contains all the parameters to send to the API endpoint
for the get role user scopes operation typically these are written to a http.Request
*/
type GetRoleUserScopesParams struct {

	/*EmptyHeader
	  The access control list header value encoded as base64 - assigned by the API Gateway based on user/request permissions

	*/
	EmptyHeader string
	/*XEMAIL
	  Email of the person who is requesting an access

	*/
	XEMAIL *string
	/*XREQUESTID
	  The unique request ID value - assigned/set by the API Gateway based on the login session

	*/
	XREQUESTID *string
	/*XUSERNAME
	  Username of the person who is requesting an access

	*/
	XUSERNAME *string
	/*ID
	  The role id.

	*/
	ID string
	/*Username
	  The username

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get role user scopes params
func (o *GetRoleUserScopesParams) WithTimeout(timeout time.Duration) *GetRoleUserScopesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get role user scopes params
func (o *GetRoleUserScopesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get role user scopes params
func (o *GetRoleUserScopesParams) WithContext(ctx context.Context) *GetRoleUserScopesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get role user scopes params
func (o *GetRoleUserScopesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get role user scopes params
func (o *GetRoleUserScopesParams) WithHTTPClient(client *http.Client) *GetRoleUserScopesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get role user scopes params
func (o *GetRoleUserScopesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmptyHeader adds the emptyHeader to the get role user scopes params
func (o *GetRoleUserScopesParams) WithEmptyHeader(emptyHeader string) *GetRoleUserScopesParams {
	o.SetEmptyHeader(emptyHeader)
	return o
}

// SetEmptyHeader adds the emptyHeader to the get role user scopes params
func (o *GetRoleUserScopesParams) SetEmptyHeader(emptyHeader string) {
	o.EmptyHeader = emptyHeader
}

// WithXEMAIL adds the xEMAIL to the get role user scopes params
func (o *GetRoleUserScopesParams) WithXEMAIL(xEMAIL *string) *GetRoleUserScopesParams {
	o.SetXEMAIL(xEMAIL)
	return o
}

// SetXEMAIL adds the xEMAIL to the get role user scopes params
func (o *GetRoleUserScopesParams) SetXEMAIL(xEMAIL *string) {
	o.XEMAIL = xEMAIL
}

// WithXREQUESTID adds the xREQUESTID to the get role user scopes params
func (o *GetRoleUserScopesParams) WithXREQUESTID(xREQUESTID *string) *GetRoleUserScopesParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the get role user scopes params
func (o *GetRoleUserScopesParams) SetXREQUESTID(xREQUESTID *string) {
	o.XREQUESTID = xREQUESTID
}

// WithXUSERNAME adds the xUSERNAME to the get role user scopes params
func (o *GetRoleUserScopesParams) WithXUSERNAME(xUSERNAME *string) *GetRoleUserScopesParams {
	o.SetXUSERNAME(xUSERNAME)
	return o
}

// SetXUSERNAME adds the xUSERNAME to the get role user scopes params
func (o *GetRoleUserScopesParams) SetXUSERNAME(xUSERNAME *string) {
	o.XUSERNAME = xUSERNAME
}

// WithID adds the id to the get role user scopes params
func (o *GetRoleUserScopesParams) WithID(id string) *GetRoleUserScopesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get role user scopes params
func (o *GetRoleUserScopesParams) SetID(id string) {
	o.ID = id
}

// WithUsername adds the username to the get role user scopes params
func (o *GetRoleUserScopesParams) WithUsername(username string) *GetRoleUserScopesParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get role user scopes params
func (o *GetRoleUserScopesParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoleUserScopesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Empty-Header
	if err := r.SetHeaderParam("Empty-Header", o.EmptyHeader); err != nil {
		return err
	}

	if o.XEMAIL != nil {

		// header param X-EMAIL
		if err := r.SetHeaderParam("X-EMAIL", *o.XEMAIL); err != nil {
			return err
		}

	}

	if o.XREQUESTID != nil {

		// header param X-REQUEST-ID
		if err := r.SetHeaderParam("X-REQUEST-ID", *o.XREQUESTID); err != nil {
			return err
		}

	}

	if o.XUSERNAME != nil {

		// header param X-USERNAME
		if err := r.SetHeaderParam("X-USERNAME", *o.XUSERNAME); err != nil {
			return err
		}

	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
